# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Close an SPI session
#'
#' @param spiDeviceID An identifier supplied by rpi_spi_open()
#' @return SPI identifier
#' @export
#'
spiClose <- function(spiDeviceID) {
    .Call(`_rpigpior_spiClose`, spiDeviceID)
}

#' Open an SPI session
#'
#' This assumes the SPI device is attached to bus zero. 
#'
#' @param spiChan The SPI channel to use. /dev/spidev[spiBus].[spiChan]
#' @param spiBus The SPI Bus to use, defaults to bus 0.
#' @param max_speed_hz spi transfer speed
#' @return SPI identifier
#' @export
#' @examplesIf is.rpi.spi()
#' spi_identifier <- rpi_spi_open(spiBus = 0, spiChan = 0)
#'
rpi_spi_open <- function(spiChan, spiBus = 0L, max_speed_hz = 32000000L) {
    .Call(`_rpigpior_rpi_spi_open`, spiChan, spiBus, max_speed_hz)
}

