# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Communicates with the IOCTL module
#'
#' The ioctl() system call manipulates the underlying device
#'      parameters of special files.  In particular, many operating
#'     characteristics of character special files (e.g., terminals) may
#'     be controlled with ioctl() requests.
#'
#' @param spiDeviceID an open file descriptor.
#' @param ioctlRequest A device-dependent request code. For the sake of Rcpp
#'      interface, an int is passed in, then used to look up the
#'      actual value. Macros and defines used in specifying an ioctl()
#'      request are located in the file <sys/ioctl.h>
#' @param spiControl an untyped pointer to memory
#' @return ioctl_value a list containing...
#' \itemize{
#'   \item status_value - a possible return value or -1 if there was an error
#'   \item errno - if status_value == -1, then errno equals the error number
#'   \item status_message - if status_value == -1, the error message
#' }
NULL

rpi_ioctl <- function(spiDeviceID, ioctlRequest, spiControl) {
    .Call(`_rpigpior_rpi_ioctl`, spiDeviceID, ioctlRequest, spiControl)
}

rpi_spi_cpp_read <- function() {
    .Call(`_rpigpior_rpi_spi_cpp_read`)
}

rpi_spi_read <- function() {
    .Call(`_rpigpior_rpi_spi_read`)
}

