# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rpi_spi_open <- function(dev) {
    .Call(`_rpigpior_rpi_spi_open`, dev)
}

